### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by v1rtl** [mistval/node-fetch-cache#11]
A few months ago Node.js 10 reached EOL so it's safe to use ES module syntax, e.g. this:

```js
import { fetchBuilder } from 'node-fetch-cache'
```

Is it planned to support it for node-fetch-cache? Either solely ESM or with combination of CJS fallback.

**Comment by mistval** [comment]
Hi, it should be possible to use it like this:

```js
import fetchBuilder from 'node-fetch-cache'

const fetch = fetchBuilder.withCache(new fetchBuilder.MemoryCache());
```

Please let me know if you have any trouble with that.

**Comment by v1rtl** [comment]
@mistval  seems to be working, thx!
