### ISSUE TITLE
Support for http cache (If-Modified-Since, If-None-Match)

### ISSUE THREAD

**Issue by slavb18** [mistval/node-fetch-cache#23]
Hi!

Any plans to implement http style cache with If-Modified-Since, If-None-Match  headers

e.g.
1.  check ttl cache
2. if cache exists and ttl is NOT expired, return result  from cache (currently supported),
3.  if cache exitsts, but ttl is expired, and cached response contains Last-Modified / ETag header, then issue fetch with If-Modified-Since / If-None-Match headers. If server response is 304 Not Modified, then return result from cache

**Comment by mistval** [comment]
Hi,

Have you looked at [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen) yet? I think it might be able to do what you need.

I'm personally only interested in using this package to cache everything, so I have no plans to implement more customizable caching, but would not object to PRs.
