### ISSUE TITLE
Feature: cache timeout

### ISSUE THREAD

**Issue by otherguy** [mistval/node-fetch-cache#4]
Neat!

It would be even better if you could define a cache timeout :) I work around it now by adding a URL parameter, but having it in the module would be nicer.

**Comment by mistval** [comment]
Hello, I have marked this as a feature request and will keep it in mind.

**Comment by mistval** [comment]
This is possible now in version 2.0:

```js
const  { fetchBuilder, FileSystemCache } = require('node-fetch-cache');
const fetch = fetchBuilder.withCache(new FileSystemCache({ ttl: 1000 }));
```

Please see the README for more info :)
