### ISSUE TITLE
TypeError with bun

### ISSUE THREAD

**Issue by glensc** [mistval/node-fetch-cache#44]
Please see if this is problem that can be solved in node-fetch-cache:
- https://github.com/oven-sh/bun/issues/8487

or where in the code the mismatch happens? in what project the fix needs to happen?

**Comment by mistval** [comment]
That's curious. I don't know if this package will make the leap to officially support bun but it would be nice if it worked there. I see they added a label to investigate and if it works fine on Node that makes me inclined to think it's an issue with their Node package compatibility. Will wait and see for now.

**Comment by glensc** [comment]
My gut feeling says that the problem could go away with the "native fetch" api support:
- https://github.com/mistval/node-fetch-cache/issues/31

**Comment by mistval** [comment]
I was able to reproduce this with `node-fetch-cache` v4 as shown in your linked issue https://github.com/oven-sh/bun/issues/8487. However I was not able to reproduce with v5, so this appears to be fixed. I'm not certain what the difference is. Feel free to reopen if you still see this in v5.

**Comment by glensc** [comment]
Why there are no git tags in this repo for the releases?
- https://github.com/mistval/node-fetch-cache

if you want i can send a pr to setup automatic publish if you push git tag, like in this project:
- https://github.com/glensc/node-cached_property

of course you can adapt yourself too

**Comment by glensc** [comment]
I'm guessing the changes come from node-fetch update, which is not that relevant to dig what commit exactly resolved this.

I've compared:
- [https://github.com/mistval/node-fetch-cache/compare/v4...master](https://github.com/mistval/node-fetch-cache/compare/de42561508c1894e56d55fca718782c06f14c341...8b93f02899db65559e31af5d6941517d276f7977)

**Comment by mistval** [comment]
I would welcome a PR to add automatic publish if you're up for it. As of now I just publish the main branch manually from the CLI rather than tagging.

**Comment by glensc** [comment]
can you do both, git tag and push the tag?

**Comment by mistval** [comment]
Do you want that so you can see a list of changes for each version?

**Comment by glensc** [comment]
yes. it's convenient way to see the changes between releases

**Comment by mistval** [comment]
I'll see about adding a CI job to publish at some point, so I can do that without extra steps to remember.

**Comment by glensc** [comment]
thanks. I might (no promises) send the pr at some point as well. 

there's also a way to add postPublishOnly (or similar, husky hook?) script to git tag and git push, but maybe going with CI is more straightforward and more commonly used.
